language: node_js
node_js: 8.11.4
cache: npm

jobs:
  include:
    - stage: deploy to staging
      install: skip
      script: skip
      deploy:
        provider: firebase
        edge:
          source: jgollhardt/dpl
          branch: firebase-force-opt
        project: travis-example
        token:
          secure: kG/i6I4Yo69wWAhb5anEfnBvhHm17r9bT+gfXgxYcJAikfxxdrVqOcSWRmvhnYl21PJuddvX+qoyKZnW9T4HuRE0RzA/UI1MhaiMj3br52CcgYoGQNtikhHqpzLxxGhsrDCuKY1wRKALvxeKDq6fRdtXxr7j3pAJXMdey0sHReH3UodmEvvt2zLHLWdqjKsd2GHdHMOjrH+ThQrjYm1Sn4j7bCwLK6leRONkq8Vcxjh9nGSfhnJ1Ze7cXIRjQ3GB+ei6KeKcN1MK+8EnXzCZy/jXBkP9evdQc5Y+jCiIVlb+HiUOy7BaSxxdcYZ7SDRMQcRcF2UViNN+CKnrCrTY2ES/S14fZAbLlqNUmuFZawakr4DN+8NwUWHg9iRXCRSeWuo3rLEcZUmwMh4EQkhoywmpWZPucjxHeAy7r/07t7Mc06VbD4Jr4ao9H3buAvwQ6sFFtxrHul/S3KEisJxZjd5yN53dvLyPyAY3WV1vA2Q+YXGNjlsJ7dtW4pK1wY1DByHjGNUrqR7OeuY3d/P+VX2GesxLMXYfTaIY8yw1qcp9jvoWpoXUSRbNLkI8vj5uopCHlEV38JLadXSEWoW5vyE/fc6+e6NANZIvZF9N7FjmAtsyAmrkeO6znGcMFyqa+mHTPuTezeBEaEhlAkrIJbFVIb9fq+mzDN9dSBqESnY=
        # force: true
